apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi-host
  name: fastapi-host
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-host
  template:
    metadata:
      labels:
        app: fastapi-host
    spec:
      containers:
        - image: nospamplease/fastapi-host:v2
          name: fastapi-host
